version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=bridge-db
    ports:
      - '5434:5434'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local